# ====================================================
# Drug-Target Interaction Analysis using Public Datasets
# Author: Hussein
# Description: This script performs comparative analysis of drug-target interactions
#              using data from OpenTargets, DrugBank, and other sources.
# PS: This is similar to the work generated by the Open_Target_FUSIL_Analysis script. However, one difference is the usage of a function which I created to prioritise Disease Classes.
# ====================================================

# Load Required Libraries --------------------------------

library(tidyverse)   # For data manipulation and visualization
library(jsonlite)    # For working with JSON (if needed in future)

# Import Datasets ----------------------------------------

# --- Import MHRA SE Data ---
mhra_se_data <- read_csv("C:/Users/HP-ssd/Desktop/Short term project2/mhra/mhra_se_data.csv", 
                         col_types = cols(...1 = col_skip()))
mhra_se_data <- mhra_se_data %>%
  na.omit()  # Remove NA values

# --- Import Human Gene Paralogues ---
human_gene_paralogues <- read_csv("C:/Users/HP-ssd/Desktop/Short term project2/paralogues/human_gene_paralogues.csv", 
                                  col_types = cols(...1 = col_skip()))

# --- Import FUSIL Data ---
fusil <- read_csv("C:/Users/HP-ssd/Desktop/Short term project2/fusil.csv")

# --- Import OpenTargets Drug Data ---
opentarget_data <- read_csv("C:/Users/HP-ssd/Desktop/Short term project2/Open Target drug data/Opentarget_data.csv", 
                            col_types = cols(...1 = col_skip()))
opentarget_data <- opentarget_data %>%
  replace_na(list(status = 'Unknown status'))  # Fill missing 'status'

# --- Import DrugBank Data ---
DrugBank_data <- read_csv("C:/Users/HP-ssd/Desktop/Short term project2/Drug bank data/DrugBank_data.csv", 
                          col_types = cols(...1 = col_skip()))
# --- Import a List of Protein Coding GENES ---

pc_genes <- read.delim("https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/locus_groups/protein-coding_gene.txt")


# Filter for Approved Drugs -----------------------------

# --- Filter DrugBank for Approved Drugs ---
drugbank_approved <- DrugBank_data %>%
  filter(!grepl("withdrawn", groups, ignore.case = TRUE))

# --- Filter OpenTargets for Completed Status Drugs ---
opentarget_approved <- opentarget_data %>%
  filter(phase == "4" | status == "Completed")


# Compare Datasets ---------------------------------------

# --- Count unique drugs in each dataset ---
count_drugs_opentarget <- n_distinct(opentarget_approved$prefName)
count_drugs_drubank <- n_distinct(drugbank_approved$name)

# --- Prepare data for visualization ---
dataset_names <- c("Open_Targets", "Drug_Bank")
unique_drug_counts <- c(3563, 2146)

plot_data <- data.frame(
  Dataset = dataset_names,
  Unique_Drugs = unique_drug_counts
)

# --- Bar Plot: Number of Unique Drugs ---
ggplot(plot_data, aes(x = Dataset, y = Unique_Drugs)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(
    title = "Unique Drugs in Each Dataset",
    x = "Dataset",
    y = "Number of Unique Drugs"
  ) +
  theme_minimal()


# Degree Distribution - OpenTargets ----------------------

# --- Drugs per Target ---
nb_drugs_per_target_opentarget <- opentarget_approved %>%
  dplyr::select(approvedSymbol, prefName) %>%
  unique() %>%
  count(approvedSymbol)

# --- Targets per Drug ---
nb_target_per_drug_opentarget <- opentarget_approved %>%
  dplyr::select(approvedSymbol, prefName) %>%
  unique() %>%
  count(prefName)

# --- Rename for clarity ---
colnames(nb_drugs_per_target_opentarget) <- c("name", "count")
colnames(nb_target_per_drug_opentarget) <- c("name", "count")

# --- Frequency of Degrees for Targets ---
target_degree_freq <- nb_drugs_per_target_opentarget %>%
  count(count, name = "frequency") %>%
  mutate(category = "Drugs per Target", degree = count) %>%
  dplyr::select(degree, frequency, category)

# --- Frequency of Degrees for Drugs ---
drug_degree_freq <- nb_target_per_drug_opentarget %>%
  count(count, name = "frequency") %>%
  mutate(category = "Targets per Drug", degree = count) %>%
  dplyr::select(degree, frequency, category)

# --- Combine & Visualize ---
degree_distribution <- bind_rows(target_degree_freq, drug_degree_freq)

# Linear scale plot
ggplot(degree_distribution, aes(x = degree, y = frequency, color = category)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Degree Distribution in Open Targets Bipartite Network",
    x = "Degree (Number of Interactions)",
    y = "Frequency",
    color = "Category"
  ) +
  theme_minimal()

# Log-log scale plot
ggplot(degree_distribution, aes(x = degree, y = frequency, color = category)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10() +
  scale_y_log10() +
  labs(
    title = "Degree Distribution in Open Targets Bipartite Network (Log-Log Scale)",
    x = "Degree (log scale)",
    y = "Frequency (log scale)",
    color = "Category"
  ) +
  theme_minimal()


# Degree Distribution - DrugBank -------------------------

# --- Drugs per Target ---
nb_drugs_per_target_drugbank <- drugbank_approved %>%
  dplyr::select(name, gene_name) %>%
  unique() %>%
  na.omit() %>%
  count(gene_name)

# --- Targets per Drug ---
nb_target_per_drug_drugbank <- drugbank_approved %>%
  dplyr::select(name, gene_name) %>%
  unique() %>%
  na.omit() %>%
  count(name)

# --- Rename for clarity ---
colnames(nb_drugs_per_target_drugbank) <- c("name", "count")
colnames(nb_target_per_drug_drugbank) <- c("name", "count")

# --- Frequency of Degrees for Targets ---
target_degree_freq <- nb_drugs_per_target_drugbank %>%
  count(count, name = "frequency") %>%
  mutate(category = "Drugs per Target", degree = count) %>%
  dplyr::select(degree, frequency, category)

# --- Frequency of Degrees for Drugs ---
drug_degree_freq <- nb_target_per_drug_drugbank %>%
  count(count, name = "frequency") %>%
  mutate(category = "Targets per Drug", degree = count) %>%
  dplyr::select(degree, frequency, category)

# --- Combine & Visualize ---
degree_distribution <- bind_rows(target_degree_freq, drug_degree_freq)

# Linear scale plot
ggplot(degree_distribution, aes(x = degree, y = frequency, color = category)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Degree Distribution in DrugBank Bipartite Network",
    x = "Degree (Number of Interactions)",
    y = "Frequency",
    color = "Category"
  ) +
  theme_minimal()

# Log-log scale plot
ggplot(degree_distribution, aes(x = degree, y = frequency, color = category)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  scale_x_log10() +
  scale_y_log10() +
  labs(
    title = "Degree Distribution in DrugBank Bipartite Network (Log-Log Scale)",
    x = "Degree (log scale)",
    y = "Frequency (log scale)",
    color = "Category"
  ) +
  theme_minimal()



# ====================================================
# Disease Category-Level Drug Analysis using FUSIL Bins
# Author: Hussein
# Description: This script processes ontology mappings and classifies drug-target
#              genes into high-level disease classes and FUSIL sensitivity bins.
# ====================================================


# Load EFO Ontology Data ----------------------------------

# Import top-level EFO ancestor terms
efo_ancestor_terms <- read_delim("C:/Users/HP-ssd/Desktop/Short term project2/Analysis script/ontologies scripts/ontologies data wrangling/data_efo/efo_ancestor_terms.txt", 
                                 delim = "\t", escape_double = FALSE, trim_ws = TRUE)


# Clean EFO DataFrame --------------------------------------

# Remove "efo:" prefix and replace "_" with ":" for standardization
efo_ancestor_terms$efo_term_id <- gsub("^efo:", "", efo_ancestor_terms$efo_term_id)
efo_ancestor_terms$efo_ancestor_id <- gsub("^efo:", "", efo_ancestor_terms$efo_ancestor_id)

efo_ancestor_terms$efo_term_id <- sub("_", ":", efo_ancestor_terms$efo_term_id)
efo_ancestor_terms$efo_ancestor_id <- sub("_", ":", efo_ancestor_terms$efo_ancestor_id)


# Define Priority Order for Disease Classes ----------------

priority <- c(
  "hereditary disease", "cancer or benign tumor", "cardiovascular disease",
  "nervous system disease", "psychiatric disorder", "disorder of development or morphogenesis",
  "endocrine system disease", "respiratory system disease", "musculoskeletal system disease",
  "digestive system disease", "connective tissue disease", "metabolic disease",
  "reproductive system disease", "urinary system disease", "hematologic disease",
  "disorder of visual system", "immune system disease", "integumentary system disease",
  "infectious disease"
)

# Function to assign ranking to categories
rank_ancestor <- function(x) {
  match(x, priority, nomatch = length(priority) + 1L)
}


# Create Table of Labelled Disease Classes -----------------

label_tbl <- efo_ancestor_terms %>%
  group_by(efo_term_id, efo_term_description) %>%
  summarise(
    all_categories = list({
      cats <- unique(efo_ancestor_description)
      cats[order(rank_ancestor(cats), cats)]  # rank then alphabetically
    }),
    .groups = "drop"
  ) %>%
  mutate(
    primary_category    = map_chr(all_categories, 1L),  # primary = highest priority
    all_categories_json = map_chr(all_categories, toJSON, auto_unbox = TRUE)
  )

# Final clean disease term mapping
efo_terms_df <- label_tbl %>%
  dplyr::select(1, 2, 4) %>%
  unique()


# Join Ontology Terms with OpenTargets ----------------------

efo_ancestor_terms_joined <- opentarget_approved %>%
  full_join(efo_terms_df, by = c("label" = "efo_term_description")) %>%
  na.omit()


# Prepare Drug-Gene Mappings -------------------------------

# Unique drug-gene combinations
drug_gene <- efo_ancestor_terms_joined %>%
  dplyr::select(approvedSymbol, prefName) %>%
  unique()

# Join with FUSIL data
drug_fusil <- fusil %>%
  full_join(drug_gene, by = c("gene_symbol" = "approvedSymbol")) %>%
  na.omit() %>%
  dplyr::select(3, 4, 5)

# Count total genes per FUSIL bin
count_fusil_genes <- drug_fusil %>%
  count(fusil)


# Compute FUSIL Distribution by Disease Class --------------

# Get all unique disease categories
unique_drug_indication_class <- unique(efo_ancestor_terms_joined$primary_category)

# Initialize result list
fusil_by_class <- list()

# Loop through each disease class
for (cls in unique_drug_indication_class) {
  
  # Filter for current class
  drug_gene <- efo_ancestor_terms_joined %>%
    filter(primary_category == cls) %>%
    dplyr::select(approvedSymbol, prefName) %>%
    distinct()
  
  # Join with FUSIL, calculate percentages
  tmp <- fusil %>%
    full_join(drug_gene, by = c("gene_symbol" = "approvedSymbol")) %>%
    na.omit() %>%
    dplyr::select(3, 4, 5) %>%
    count(fusil) %>%
    left_join(count_fusil_genes, by = "fusil") %>%
    mutate(
      percentage = (n.x / n.y) * 100,
      drug_class = cls
    )
  
  tmp$fusil <- factor(
    tmp$fusil,
    levels = c("CL", "DL", "SV", "VP", "VnP")  # standard order
  )
  
  fusil_by_class[[cls]] <- tmp
  
  # Plot per disease class
  p <- ggplot(tmp, aes(x = fusil, y = percentage, fill = fusil)) +
    geom_bar(stat = "identity") +
    labs(
      title = paste(cls, "Drugs Distribution among the FUSIL Categories"),
      x = "FUSIL bin",
      y = "Count of Drugs / Targets"
    )
  
  print(p)  # Display
}


# Combine and Clean FUSIL-Class Data -----------------------

combined_fusil <- bind_rows(fusil_by_class)

combined_fusil <- combined_fusil %>%
  group_by(fusil) %>%
  mutate(drug_class = fct_reorder(drug_class, percentage))  # reorder classes


# Remove Irrelevant or Low-Support Categories --------------

drug_classes_to_remove <- c(
  "urogenital neoplasm", "disease related to transplantation", 
  "connective tissue disease", "poisoning", "syndromic disease", 
  "obstetric disorder", "post-infectious disorder", "chromosomal disorder", "disorder of visual system")


combined_fusil_filtered <- combined_fusil %>%
  filter(!(drug_class %in% drug_classes_to_remove))


# ---------------- PLOT 1: Facet by FUSIL Bin ----------------

ggplot(combined_fusil_filtered, aes(x = drug_class, y = percentage, fill = drug_class)) +
  geom_bar(stat = "identity", nrow = 1) +
  facet_wrap(~ fusil) +
  coord_flip() +
  labs(
    title = "Distribution of Disease Classes Within Each FUSIL Bin",
    x = "Disease Class",
    y = "Percentage of Drug-Target Genes"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "none"
  )


# ---------------- PLOT 2: Facet by Disease Class ----------------

ggplot(combined_fusil_filtered, aes(x = fusil, y = percentage, fill = drug_class)) +
  geom_bar(stat = "identity", nrow = 1) +
  facet_wrap(~ drug_class) +
  coord_flip() +
  labs(
    title = "Distribution of Disease Classes Within Each FUSIL Bin",
    x = "FUSIL bin",
    y = "Percentage of Drug-Target Genes"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position = "none"
  ) +
  geom_text(aes(label = round(percentage, 1)), hjust = -0.2, size = 3)
